//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int id { get; set; }
        public int departmentId { get; set; }
        public string description { get; set; }
        public int plantId { get; set; }
        public string stamp { get; set; }
    }
}
