//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpDept
    {
        public int id { get; set; }
        public Nullable<int> partDeptID { get; set; }
        public Nullable<int> operationID { get; set; }
    }
}
