//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartDepartment
    {
        public int id { get; set; }
        public string partID { get; set; }
        public Nullable<int> deptID { get; set; }
        public Nullable<int> sequence { get; set; }
        public double cost { get; set; }
        public double weightlbs { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<System.DateTime> dateCost { get; set; }
    }
}
