//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartCustomer
    {
        public int PartCustID { get; set; }
        public string PartID { get; set; }
        public int CustID { get; set; }
    }
}
