//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapDetail
    {
        public int id { get; set; }
        public int scrapId { get; set; }
        public int reasonId { get; set; }
        public int machineId { get; set; }
        public int quantity { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<short> employeeNumber { get; set; }
    }
}
