//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string partId { get; set; }
        public string departmentId { get; set; }
        public string plantId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string operationId { get; set; }
        public Nullable<double> unitCost { get; set; }
        public Nullable<double> unitWeight { get; set; }
        public string cancelled { get; set; }
    }
}
